### ISSUE TITLE
Request for evaluation data in csv format

### ISSUE THREAD

**Issue by w-m** [wyf0912/ContextGS#4]
Thanks for your contribution to 3DGS compression! It has been [requested](https://github.com/w-m/3dgs-compression-survey/issues/11) to add your method to the [3DGS compression survey](https://w-m.github.io/3dgs-compression-survey/).

We kindly request that you publish your results in the following format: https://github.com/w-m/3dgs-compression-survey?tab=readme-ov-file#including-your-own-results

We will then be able to add the method to the table and the plots in the survey.

Please note the section on [testing conventions](https://github.com/w-m/3dgs-compression-survey?tab=readme-ov-file#important-3dgs-testing-conventions), to ensure that the results produced are directly comparable with other methods.

We're happy to assist with any questions & issues, just drop us a comment.

**Comment by wyf0912** [comment]
Hi, thanks for contacting us. I have uploaded them for reference.

**Comment by myla** [comment]
Thank you @wyf0912 i've merged your data.
